### PR TITLE
Add eslint linter with prettier for code formating

### PR DESCRIPTION
**Pull request by smalluban**
* Adds `eslint` and `prettier` to the project
* Fixes formatting and other found eslint issues
* Adds `Tests` github action

Disclaimer: For now, it must disable running scripts when `npm ci` is invoked.

Commits with source code changes:
3fc725e965d6e542eaed72c0dd3be460cfa1dedc
ace767646c490ffb2eac491bde9017fb79e1aa78

### CODE REVIEW

**Comment by philipp-classen** [comment]
Looks good! Maybe we can make the eslint defaults a bit stricter, for instance, it complained about

```
    var x = '4'
    var y_z = '4' + 2
```

... but was happy when I changed it to

```
    var x = '4';
    var y_z = '4' + 2;
```

But should not stop merging.

**Review by philipp-classen — APPROVED** [review]

**Comment by smalluban** [comment]
@philipp-classen I am not sure if your comment is more about semicolon or string and number concatenation ;)

**Review by chrmod — APPROVED** [review]
Perfect!

**Comment by philipp-classen** [comment]
> @philipp-classen I am not sure if your comment is more about semicolon or string and number concatenation ;)

Was just trying to write the worst JavaScript that I can think of. :-)

Apparently, it catches the missing semicolons, but misses the other aspects (e.g. "var"). This is the diff that I had locally:

```
diff --git a/src/worker/bugs-matcher.js b/src/worker/bugs-matcher.js
index 0313665..8f3aea3 100644
--- a/src/worker/bugs-matcher.js
+++ b/src/worker/bugs-matcher.js
@@ -12,6 +12,8 @@
 function processUrl(src) {
   try {
     const res = new URL(src);
+    var x = '4';
+    var y_z = '4' + 2;
     return res;
   } catch (e) {
     return {
```

Now `npm run lint` passes. My expectation would be that it complains about that code.

**Comment by smalluban** [comment]
I think there is a rule which forceses to use `let` and `const` over the `var`, but it must not be included in `eslint:recommended` preset.

**Pull request merged**
